version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: wms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wms
    ports:
      - "3307:3306"   # host:container
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
